### ISSUE TITLE
Cannot set BlockDeviceMappings for EC2 instance

### ISSUE THREAD

**Issue by jeffzoch** [treelogic-swe/aws-mock#51] opened 2018-10-04 22:56 UTC
Would be really useful if all of the fields for an ec2 instance were exposed. For example, I would like to test taking snapshots on block devices, which requires me getting an instance's block device mappings and iterating over them to call "createSnapshot". Currently only 4 fields are actually set when I run an instance.

**Comment by maxiaohao** [comment] 2018-12-26 10:34
Hi @jeffzoch thanks for asking this question. 
For now we are not mapping all the fields as it takes much resource to maintain all of them. Instead, we encourage users to add mock fields by their own on-demand. 
In your case, I guess you can achieve that by setting some mock values for the `runningInstancesItemType.blockDeviceMapping.` in around https://github.com/treelogic-swe/aws-mock/blob/master/src/main/java/com/tlswe/awsmock/ec2/control/MockEC2QueryHandler.java#L1124
And preferably, we would like you to put your work into a pull request so that we can review and merge that feature into aws-mock. 
Thank you!

**Comment by nottoseethesun** [comment] 2019-02-18 17:58
Closing as the issue is addressed; as mentioned, we welcome PRs.

**Closed by nottoseethesun** 2019-02-18 17:58 UTC
Labels: enhancement
